### ISSUE TITLE
ssmstore issue with runway 1.18.3 and 1.4.4

### ISSUE THREAD

**Issue by newbeeeeeee** [onicagroup/runway#1352]
I am having a really weird issue with ssmtore in cfngin/stacker file. This module was working fine for a long time but now I am getting the following error. I have checked to ensure that the runway role has access to ssm:* and also the ssm parameter exists:

Couldn't resolve lookup in variable `xxx`, lookup: ${Lookup<Literal<'ssmstore'> Concatenation[Literal<'ca-central-1@xxxx'>]>}: (<class 'IndexError'>) list index out of range
Traceback (most recent call last):
  File "site-packages/runway/variables.py", line 657, in resolve
  File "site-packages/runway/cfngin/lookups/handlers/ssmstore.py", line 71, in handle
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/runway/variables.py", line 118, in resolve
  File "site-packages/runway/variables.py", line 675, in resolve
runway.cfngin.exceptions.FailedLookup: Failed lookup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/runway/cfngin/plan.py", line 133, in _run_once
  File "site-packages/runway/cfngin/actions/diff.py", line 193, in _diff_stack
  File "site-packages/runway/cfngin/stack.py", line 243, in resolve
  File "site-packages/runway/variables.py", line 53, in resolve_variables
  File "site-packages/runway/variables.py", line 121, in resolve
runway.cfngin.exceptions.FailedVariableLookup: Couldn't resolve lookup in variable `xxx`, lookup: ${Lookup<Literal<'ssmstore'> Concatenation[Literal<'ca-central-1@xxxx>]>}: (<class 'IndexError'>) list index out of range

I am not sure what could be missing since I use ssmstore all the time and never had an issue.

**Comment by newbeeeeeee** [comment]
I had the wrong account id in runway configuration file. Closing issue.
