### ISSUE TITLE
user_pool_id_retriever hook failing with ValidationError

### ISSUE THREAD

**Issue by mbordash2** [onicagroup/runway#1405]
### Bug Description

Creating a staticsite with an existing `user_pool_arn` defined results in a validation error in the `user_pool_id_retriever` hook.

```
[runway] 01-dependencies.yaml:deploy (in progress)
[runway] executing pre_deploy hooks: runway.cfngin.hooks.staticsite.auth_at_edge.callback_url_retriever.get, runway.cfngin.hooks.staticsite.auth_at_edge.user_pool_id_retriever.get
kwargs:{'context': <runway.context._cfngin.CfnginContext object at 0x106fd6040>, 'provider': <runway.cfngin.providers.aws.default.Provider object at 0x107c13fa0>, 'user_pool_arn': 'arn:aws:cognito-idp:us-east-1:0123456789:userpool/us-east-1_XYZ'}
[runway] hook runway.cfngin.hooks.staticsite.auth_at_edge.user_pool_id_retriever.get threw an exception
Traceback (most recent call last):
  File "/Users/mbordash/Library/Caches/pypoetry/virtualenvs/xxx/lib/python3.9/site-packages/runway/cfngin/hooks/utils.py", line 123, in handle_hooks
    result = cast(Any, method(context=context, provider=provider, **kwargs))
  File "/Users/mbordash/Library/Caches/pypoetry/virtualenvs/xxx/lib/python3.9/site-packages/runway/cfngin/hooks/staticsite/auth_at_edge/user_pool_id_retriever.py", line 32, in get
    args = HookArgs.parse_obj(kwargs)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HookArgs
created_user_pool_id
  field required (type=value_error.missing)
[runway] 1 validation error for HookArgs
created_user_pool_id
  field required (type=value_error.missing)
make: *** [deploy-dev] Error 1
```

Creating a staticsite without a `user_pool_arn` defined also results in a validation error in the `user_pool_id_retriever` hook.

```
[runway] 02-staticsite.yaml:deploy (in progress)
[runway] executing pre_deploy hooks: runway.cfngin.hooks.staticsite.build_staticsite.build, runway.cfngin.hooks.staticsite.auth_at_edge.user_pool_id_retriever.get, runway.cfngin.hooks.staticsite.auth_at_edge.domain_updater.update, runway.cfngin.hooks.staticsite.auth_at_edge.lambda_config.write
[runway] skipped build; hash already deployed
kwargs:{'context': <runway.context._cfngin.CfnginContext object at 0x1074a76d0>, 'provider': <runway.cfngin.providers.aws.default.Provider object at 0x1070ddfa0>, 'created_user_pool_id': 'us-east-1_XYZ', 'user_pool_arn': None}
[runway] hook runway.cfngin.hooks.staticsite.auth_at_edge.user_pool_id_retriever.get threw an exception
Traceback (most recent call last):
  File "/Users/mbordash/Library/Caches/pypoetry/virtualenvs/xxx/lib/python3.9/site-packages/runway/cfngin/hooks/utils.py", line 123, in handle_hooks
    result = cast(Any, method(context=context, provider=provider, **kwargs))
  File "/Users/mbordash/Library/Caches/pypoetry/virtualenvs/xxx/lib/python3.9/site-packages/runway/cfngin/hooks/staticsite/auth_at_edge/user_pool_id_retriever.py", line 32, in get
    args = HookArgs.parse_obj(kwargs)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HookArgs
user_pool_arn
  none is not an allowed value (type=type_error.none.not_allowed)
[runway] 1 validation error for HookArgs
user_pool_arn
  none is not an allowed value (type=type_error.none.not_allowed)
make: *** [deploy-dev] Error 1
```

### Expected Behavior

It should not be necessary to specify both `user_pool_arn` and  `created_user_pool_id` in order deploy a static site and pass the validation check being performed.

### Steps To Reproduce

Attempt to deploy a staticsite using  the `staticsite_create_user_pool: false` and provide a `staticsite_user_pool_arn` value.  It should not have to be a valid user pool to trigger the validation check to fail.

### Runway version

2.6.1

### Installation Type

pypi (pip, pipenv, poetry, etc)

### OS / Environment

- OS: macOS 12.1
- python version: 3.9.12

**Comment by mbordash2** [comment]
This update to `user_pool_id_retriever.py` class variable declarations appears to be working around the issue for the time being.

```
class HookArgs(HookArgsBaseModel):
    """Hook arguments."""

    created_user_pool_id: str = None
    """The ID of the created Cognito User Pool."""

    user_pool_arn: str = None
    """The ARN of the supplied User pool."""
```

**Comment by jake-skipper** [comment]
> This update to `user_pool_id_retriever.py` class variable declarations appears to be working around the issue for the time being.
> 
> ```
> class HookArgs(HookArgsBaseModel):
>     """Hook arguments."""
> 
>     created_user_pool_id: str = None
>     """The ID of the created Cognito User Pool."""
> 
>     user_pool_arn: str = None
>     """The ARN of the supplied User pool."""
> ```

Hi @mbordash2 - This one is hard to reproduce using an example site, since the lab environment isn't letting me set up a good CloudFront solution (no domain, CloudFormation is required for the auth options), and the IDP I am feeding in isn't fully configured. I was at least able to get the error you posted to fire, any chance you could try the following against the site that threw the error? https://github.com/jake-skipper/runway/commit/a884280eaa55456422e59a4e6e92a849a3048658
