### ISSUE TITLE
[BUG] Getting error message runway fresh install TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by vasilax** [onicagroup/runway#1414]
### Bug Description

Running runway for the first time on a fresh Amazon Linux2 machine, or on MacOS gives the following error:
runway] using backend values from runway.yml
Traceback (most recent call last):
  File "runway-script.py", line 2, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "runway/_cli/main.py", line 33, in invoke
  File "click/core.py", line 1659, in invoke
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "click/decorators.py", line 26, in new_func
  File "runway/_cli/commands/_plan.py", line 47, in plan
  File "runway/core/__init__.py", line 130, in plan
  File "runway/core/__init__.py", line 260, in __run_action
  File "runway/core/components/_deployment.py", line 313, in run_list
  File "runway/core/components/_deployment.py", line 163, in plan
  File "runway/core/components/_deployment.py", line 273, in __sync
  File "runway/core/components/_deployment.py", line 188, in run
  File "runway/core/components/_module.py", line 325, in run_list
  File "runway/core/components/_module.py", line 212, in plan
  File "runway/core/components/_module.py", line 242, in run
  File "runway/module/terraform.py", line 354, in plan
  File "runway/module/terraform.py", line 552, in run
  File "runway/module/terraform.py", line 444, in terraform_init
  File "runway/module/terraform.py", line 259, in gen_command
  File "backports/cached_property/__init__.py", line 80, in __get__
  File "runway/module/terraform.py", line 186, in tf_bin
  File "runway/env_mgr/tfenv.py", line 377, in install
  File "backports/cached_property/__init__.py", line 80, in __get__
  File "runway/env_mgr/tfenv.py", line 307, in version
  File "runway/env_mgr/tfenv.py", line 119, in get_available_tf_versions
  File "distutils/version.py", line 52, in __lt__
  File "distutils/version.py", line 337, in _cmp
TypeError: '<' not supported between instances of 'str' and 'int'
[2710] Failed to execute script 'runway-script' due to unhandled exception!

Runway version 2.6.1 (also tried with 2.4.4)

Same repo with runway configuration and same runway version run successfully on other machines where runway was running in the past

### Expected Behavior

Successful run or runway

### Steps To Reproduce

- Spin up a new Linux Amazon2 machine with admin IAM policy/role
- sudo yum update -y
- installing runway using curl, adding execute permissions and moving to /usr/bin
- install git
- clone the repo locally
- executing ENVIRONMENT_DEPLOY=dev runway plan.
- ...
- Getting an error:
[runway] 
[runway] 
[runway] XXXXXXX:processing deployment (in progress)
[runway] XXXXXXX:processing regions sequentially...
[runway] XXXXXXX:verified current AWS account matches required account id "XXXXXXXX"
[runway] 
[runway] XXXXXX.XXXXXXX:processing module in us-east-1 (in progress)
[runway] XXXX-group-2-internal-lb:init (in progress)
[runway] using backend values from runway.yml
Traceback (most recent call last):
  File "runway-script.py", line 2, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "runway/_cli/main.py", line 33, in invoke
  File "click/core.py", line 1659, in invoke
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "click/decorators.py", line 26, in new_func
  File "runway/_cli/commands/_plan.py", line 47, in plan
  File "runway/core/__init__.py", line 130, in plan
  File "runway/core/__init__.py", line 260, in __run_action
  File "runway/core/components/_deployment.py", line 313, in run_list
  File "runway/core/components/_deployment.py", line 163, in plan
  File "runway/core/components/_deployment.py", line 273, in __sync
  File "runway/core/components/_deployment.py", line 188, in run
  File "runway/core/components/_module.py", line 325, in run_list
  File "runway/core/components/_module.py", line 212, in plan
  File "runway/core/components/_module.py", line 242, in run
  File "runway/module/terraform.py", line 354, in plan
  File "runway/module/terraform.py", line 552, in run
  File "runway/module/terraform.py", line 444, in terraform_init
  File "runway/module/terraform.py", line 259, in gen_command
  File "backports/cached_property/__init__.py", line 80, in __get__
  File "runway/module/terraform.py", line 186, in tf_bin
  File "runway/env_mgr/tfenv.py", line 377, in install
  File "backports/cached_property/__init__.py", line 80, in __get__
  File "runway/env_mgr/tfenv.py", line 307, in version
  File "runway/env_mgr/tfenv.py", line 119, in get_available_tf_versions
  File "distutils/version.py", line 52, in __lt__
  File "distutils/version.py", line 337, in _cmp
TypeError: '<' not supported between instances of 'str' and 'int'
[2710] Failed to execute script 'runway-script' due to unhandled exception!

### Runway version

2.6.1 and 2.4.4

### Installation Type

direct download (curl, wget, etc)

### OS / Environment

On not working machines
- OS: Amazon Linux 2 
- python2 version: 2.7.18
- python3 version: 3.7.10
- terraform version: 1.1.0

Tried also on Ubuntu and MacOS BigSur 11.4 - same errors

On working machine 
- MacOS Catalina 10.15.7
- python2 version:  2.7.17
- python3 version:  3.8.2
- terraform version: 1.1.0

**Comment by mbordash2** [comment]
@vasilax please try `v2.6.2`.
