### ISSUE TITLE
[BUG] Packaging library version 22.0 causes crash

### ISSUE THREAD

**Issue by jake-skipper** [onicagroup/runway#1729]
### Bug Description

A Runway setup that previously worked is now returning the following error:

```
DEPLOY_ENVIRONMENT=aac poetry run runway plan
Traceback (most recent call last):
  File "/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/bin/runway", line 5, in <module>
    from runway._cli.main import cli
  File "/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/lib/python3.10/site-packages/runway/_cli/__init__.py", line 2, in <module>
    from .main import cli
  File "/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/lib/python3.10/site-packages/runway/_cli/main.py", line 11, in <module>
    from . import commands, options
  File "/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/lib/python3.10/site-packages/runway/_cli/commands/__init__.py", line 7, in <module>
    from ._gen_sample import gen_sample
  File "/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/lib/python3.10/site-packages/runway/_cli/commands/_gen_sample/__init__.py", line 20, in <module>
    from ._tf import tf
  File "/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/lib/python3.10/site-packages/runway/_cli/commands/_gen_sample/_tf.py", line 9, in <module>
    from ....env_mgr.tfenv import get_latest_tf_version
  File "/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/lib/python3.10/site-packages/runway/env_mgr/tfenv.py", line 33, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/vscode/.cache/pypoetry/virtualenvs/python-lambda-dev-9UO65exq-py3.10/lib/python3.10/site-packages/packaging/version.py)
```

This seems to happen when `packaging` is at version `22.0`; however, the problem goes away when pinning `packaging` to version `21.3`.

### Expected Behavior

Runway should either be updated to support the most recent version of `packaging`, or have library requirements adjusted so that `21.3` is installed.

### Steps To Reproduce

I am able to reproduce this by doing a fresh Runway install via `pip`, and performing a `runway plan`.

### Runway version

2.6.3

### Installation Type

pypi (pip, pipenv, poetry, etc)

### OS / Environment

- OS: Ubuntu 22.04
- python version: 3.10.0

**Comment by u362jsim** [comment]
Having the same issue here. How did you pin your packaging version?

 We're trying to use 
`pip install --upgrade packaging==21.3` after `pipenv install runway`, but we're still running into the error. We believe `pipenv install runway` still installs the latest packaging version in the environment and causes our line to not do anything/not get used. 

Would be greatly appreciated if you let me know, thank you!

**Comment by jake-skipper** [comment]
Hello @u362jsim - sorry for the delayed response, been out of office.

In my case, I am using Poetry for python package management, and I have the following:

```
[tool.poetry]
name = "python-lambda-dev-example"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.24.89"

[tool.poetry.dev-dependencies]
runway = "^2.6.3"
packaging = "^21.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

If you're using Pipenv, you will likely want to do the same type of pinning in your `Pipfile` (looks like that is documented at https://pipenv-fork.readthedocs.io/en/latest/basics.html#specifying-versions-of-a-package ) - it's likely the install you're doing via pip is being overridden when you tell pipenv to install after.

**Comment by u362jsim** [comment]
Thank you very much! We made it work with mods to our pipfile

**Comment by cloudwitch** [comment]
Thanks Jake!
