### ISSUE TITLE
[BUG] I am trying to runway in my github actions. THe pipeline used to run well before but now its not working.

### ISSUE THREAD

**Issue by sagargulabani** [onicagroup/runway#2060]
### Bug Description

I am running runway in my github actions pipeline. THis pipeline used to work well upto 2 months ago. However the pipeline has stopped working recently. When I dug deeper into the issue I found out the botocore wheel that is downloaded has services-2.json file as a compressed file, which means it is (services-2.json.gz). However as per the error, the code is looking for services-2.json

This looks like an issue with the newer versions of botocore after 1.32. 

Here is the entire error.

```
Run runway deploy --ci -e $DEPLOY_ENVIRONMENT --tag account:root
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/bin/runway", line 5, in <module>
    from runway._cli.main import cli
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/_cli/__init__.py", line 2, in <module>
    from .main import cli
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/_cli/main.py", line 11, in <module>
    from . import commands, options
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/_cli/commands/__init__.py", line 7, in <module>
    from ._gen_sample import gen_sample
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/_cli/commands/_gen_sample/__init__.py", line [13](https://github.com/tech-speedyy/speedyy-management/actions/runs/7246506132/job/19738576590#step:7:14), in <module>
    from ._k8s_cfn_repo import k8s_cfn_repo
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/_cli/commands/_gen_sample/_k8s_cfn_repo.py", line 12, in <module>
    from ....blueprints.k8s.k8s_workers import NodeGroup
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/blueprints/k8s/k8s_workers.py", line 37, in <module>
    class NodeGroup(Blueprint):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/blueprints/k8s/k8s_workers.py", line 55, in NodeGroup
    "allowed_values": get_valid_instance_types(),
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/runway/blueprints/k8s/k8s_workers.py", line 33, in get_valid_instance_types
    with open(ec2_service_file, "r", encoding="utf-8") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/botocore/data/ec2/2016-11-[15](https://github.com/*********/********/actions/runs/7246506132/job/19738576590#step:7:16)/service-2.json'
```

I am facing this error locally also.

### Expected Behavior

I expect my pipeline to run successfully

### Runway version

2.6.11

### Installation Type

pypi (pip, pipenv, poetry, etc)

### OS / Environment

- OS: ubuntu 20.04
- python version - 3.11
- botocore version -  1.34.2

### Anything else?

How can I resolve this issue.

**Comment by jake-skipper** [comment]
@sagargulabani - Thanks for the report. I am digging into this one this afternoon to see if we can either provide a fix or advise on a previous version that is unaffected. I hope to give you an update soon.

**Comment by jake-skipper** [comment]
@sagargulabani - Good afternoon. Can you please give version `2.6.12` a try? https://github.com/onicagroup/runway/releases/tag/v2.6.12

This is a version we've been working on for some time to remove support for Python 3.8 which is going end of life soon. We were able to test a fix for the issue you were encountering and pulled it in to this release. Thanks, looking forward to your confirmation.

**Comment by sagargulabani** [comment]
it works. Thank you so much.

**Comment by jake-skipper** [comment]
Great to hear, thank you for the bug report!
