### ISSUE TITLE
Runway issue while updating the Cloudformation Stack

### ISSUE THREAD

**Issue by sasiarjun** [onicagroup/runway#22]
We are facing Runway issue while updating the Cloudformation Stack after changing the value in the env file.  While updating the stack with the new value, the job fails with the below error.
However, rerunning the job passes after deleting the stack.  Please find the job details below

Error:
Changes
- Modify ParameterStore (AWS::SSM::Parameter)
[2018-12-04T15:19:27] EOF when reading a line
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/plan.py", line 89, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/actions/build.py", line 311, in _launch_stack
    stack_policy=stack_policy,
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/providers/aws/default.py", line 798, in update_stack
    stack_policy=stack_policy, **kwargs)
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/providers/aws/default.py", line 838, in interactive_update_stack
    include_verbose=True,
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/providers/aws/default.py", line 148, in ask_for_approval
    '/'.join(approval_options)))
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/ui.py", line 48, in ask
    return get_raw_input(message)
  File "/usr/lib/python2.7/site-packages/runway/embedded/stacker/ui.py", line 11, in get_raw_input
    return raw_input(message)
EOFError: EOF when reading a line
[2018-12-04T15:19:27] aws-dev-parameter-al-img changes:
Parameters Modified: KeyDescription, KeyValue

Changes:
- Modify ParameterStore (AWS::SSM::Parameter)
[2018-12-04T15:19:27] EOF when reading a line

Please help us to fix this.

**Comment by troyready** [comment]
Determined on slack to be because deploy was run without a tty present or CI env var set (at least one of the two are needed)
