### ISSUE TITLE
Static Site Auth At Edge fails to deploy from single binary builds

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#272]
The static site module type invokes the cfngin aws_lambda hook, which picks up `runway-cli` as the python executable and raises an exception when it tries to run `runway-cli -m pip ...`

Error occurred for me on a Ubuntu 20.04 system with npm-installed/ran Runway v1.7.3.

```
$ npx runway deploy
<normal output through the build of the static site>

INFO:runway.hooks.staticsite.build_staticsite:staticsite: archiving app at <repo-root>/frontend to s3://<namespace>-frontend-dependencies-artifacts-1x8zky2a7xftl/<namespace>-frontend-c37190d638ef359009f0b6c8020dffa7.zip
INFO:runway.cfngin.hooks.aws_lambda:lambda: using custom bucket: <namespace>-frontend-dependencies-artifacts-1x8zky2a7xftl
INFO:runway.cfngin.hooks.aws_lambda:lambda: using requirements.txt for dependencies
ERROR:runway.cfngin.hooks.aws_lambda:"<repo-root>/node_modules/@onica/runway/src/runway/runway-cli -m pip install -t /home/troyready/.runway_cache/cfnginnkuld5kf -r /home/troyready/.runway_cache/cfnginnkuld5kf/requirements.txt" failed with the following output:
Usage:
  runway (test|preflight)
  runway (plan|taxi) [--tag <tag>...]
  runway (deploy|takeoff) [--tag <tag>...]
  runway (destroy|dismantle) [--tag <tag>...]
  runway init
  runway gen-sample [<samplename>]
  runway whichenv
  runway envvars
  runway run-aws <awscli-args>...
  runway run-python <filename>
  runway run-stacker <stacker-args>...
  runway tfenv (install|run) [<tfenv-args>...]
  runway kbenv (install|run) [<kbenv-args>...]
  runway -h | --help
  runway --version

ERROR:runway.cfngin.hooks.utils:Method runway.hooks.staticsite.auth_at_edge.lambda_config.write threw an exception:
Traceback (most recent call last):
  File "site-packages/runway/cfngin/hooks/utils.py", line 94, in handle_hooks
  File "site-packages/runway/hooks/staticsite/auth_at_edge/lambda_config.py", line 131, in write
  File "site-packages/runway/cfngin/hooks/aws_lambda.py", line 960, in upload_lambda_functions
  File "site-packages/runway/cfngin/hooks/aws_lambda.py", line 710, in _upload_function
  File "site-packages/runway/cfngin/hooks/aws_lambda.py", line 536, in _zip_package
runway.cfngin.exceptions.PipError: A non-zero exit code was returned when invoking pip. More information can be found in the error above.
Traceback (most recent call last):
  File "runway-script.py", line 2, in <module>
  File "site-packages/runway/cli.py", line 91, in main
  File "site-packages/runway/commands/modules/deploy.py", line 55, in execute
  File "site-packages/runway/commands/modules_command.py", line 371, in run
  File "site-packages/runway/commands/modules_command.py", line 452, in _process_deployments
  File "site-packages/runway/commands/modules_command.py", line 474, in _execute_deployment
  File "site-packages/runway/commands/modules_command.py", line 511, in _process_modules
  File "site-packages/runway/commands/modules_command.py", line 594, in _deploy_module
  File "site-packages/runway/module/staticsite.py", line 76, in deploy
  File "site-packages/runway/module/staticsite.py", line 110, in _setup_website_module
  File "site-packages/runway/module/cloudformation.py", line 18, in deploy
  File "site-packages/runway/cfngin/cfngin.py", line 124, in deploy
  File "site-packages/runway/cfngin/actions/base.py", line 162, in execute
  File "site-packages/runway/cfngin/actions/build.py", line 510, in pre_run
  File "site-packages/runway/cfngin/actions/build.py", line 185, in handle_hooks
  File "site-packages/runway/cfngin/hooks/utils.py", line 94, in handle_hooks
  File "site-packages/runway/hooks/staticsite/auth_at_edge/lambda_config.py", line 131, in write
  File "site-packages/runway/cfngin/hooks/aws_lambda.py", line 960, in upload_lambda_functions
  File "site-packages/runway/cfngin/hooks/aws_lambda.py", line 710, in _upload_function
  File "site-packages/runway/cfngin/hooks/aws_lambda.py", line 536, in _zip_package
runway.cfngin.exceptions.PipError: A non-zero exit code was returned when invoking pip. More information can be found in the error above.
[54165] Failed to execute script runway-script
```

Not sure exactly what the best path forward is. From what I can tell, it used to be supported to [run pip from in python](https://stackoverflow.com/a/37389885/2547802) but that reportedly doesn't work anymore. If there was some way to do it, in binary packaging we control everything so maybe it's possible via another condition [here](https://github.com/onicagroup/runway/blob/v1.7.3/runway/cfngin/hooks/aws_lambda.py#L516) -- changing it to `runway-cli run-python ...`

**Comment by ITProKyle** [comment]
> From what I can tell, it used to be supported to run pip from in python but that reportedly doesn't work anymore.

It is still _possible_ but highly frowned upon and liable to break whatever is trying to use it this way.

https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program
