### ISSUE TITLE
Deploying a serverless module without npm installed generates an exception

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#336]
When attempting to deploy a Serverless Framework module, a stacktrace occurs if npm isn't installed.

To reproduce it, launch runway in a docker container without npm. E.g.:

```
docker run --rm -it -v `pwd`:/app ubuntu:bionic bash
apt update && apt-get install -y python3-pip
pip3 install runway  # v1.8 at time of writing
cd app
runway deploy
```

It will generate a stacktrace like the following:
```
Traceback (most recent call last):
  File "/usr/local/bin/runway", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/runway/cli.py", line 91, in main
    command_class(cli_arguments).execute()
  File "/usr/local/lib/python3.6/dist-packages/runway/commands/modules/deploy.py", line 55, in execute
    self.run(deployments=None, command='deploy')
  File "/usr/local/lib/python3.6/dist-packages/runway/commands/modules_command.py", line 371, in run
    self._process_deployments(deployments_to_run, context)
  File "/usr/local/lib/python3.6/dist-packages/runway/commands/modules_command.py", line 452, in _process_deployments
    self._execute_deployment(deployment, context, region)
  File "/usr/local/lib/python3.6/dist-packages/runway/commands/modules_command.py", line 474, in _execute_deployment
    self._process_modules(deployment, context)
  File "/usr/local/lib/python3.6/dist-packages/runway/commands/modules_command.py", line 511, in _process_modules
    self._deploy_module(module, deployment, context)
  File "/usr/local/lib/python3.6/dist-packages/runway/commands/modules_command.py", line 590, in _deploy_module
    options=module_opts
  File "/usr/local/lib/python3.6/dist-packages/runway/module/serverless.py", line 140, in __init__
    super(Serverless, self).__init__(context, path, options.copy())
  File "/usr/local/lib/python3.6/dist-packages/runway/module/__init__.py", line 161, in __init__
    self.check_for_npm()  # fail fast
  File "/usr/local/lib/python3.6/dist-packages/runway/module/__init__.py", line 183, in check_for_npm
    self.path.name)
AttributeError: 'Serverless' object has no attribute 'path'
```

It should instead be successfully printing the fatal warning message in that check_for_npm function ^.

**Comment by ITProKyle** [comment]
it's occurring because `.check_for_npm()` is being called before `super()`

can be fixed by either removing the use of `path` from the log statement or rearranging [runway/module/__init__.py#L166-L168](https://github.com/onicagroup/runway/blob/master/runway/module/__init__.py#L166-L168) to

```python
        options = options or {}
        super(RunwayModuleNpm, self).__init__(context, path, options)
        self.check_for_npm()  # fail fast
```
