### ISSUE TITLE
[BUG] Runway Deploy on pipelines for multiple deployments using CI=1

### ISSUE THREAD

**Issue by rnour-onica** [onicagroup/runway#348]
Hello everyone,

Im trying to run runway deploy using Bitbucket pipeline.

I have multiple deployments, and some of the deployments has multiple modules for a specific region.

I have the following project structure:
```
--- runway.yaml
--- production
     -- networking
         -- stacks.yaml
         -- modules
             -- vidigami_network.py
     -- auroradb
         -- stacks.yaml
         -- modules
             -- aurora.py
     -- cloudfront
         -- stacks.yaml
         -- modules
             -- aurora.py
```

sample runway.yaml is as follows:

```
deployments:
  - modules:
      - auroradb
      - networking
    regions:
      - ca-central-1
    environments:
      production:
        <<: *common-parameters

  - modules:
      - cloudfront
    regions:
      - us-east-1
    environments:
      production:
        <<: *common-parameters
```

and then stacks.yaml looks as follows, for example for the networking module:

```
sys_path: ./
stacks:
  networking:
    class_path: modules.networks.VidigamiNetworkBluePrint
```

and on running the pipeline, we use the following commands:

```      
 - pip install pipenv
 - pipenv install runway
 - cd production
 - pipenv install --skip-lock
 - export CI=1
 - pipenv run runway deploy
```

When running 'CI=1 runway deploy' in Bitbucket pipeline, sometimes the pipeline run succeeds and deploys all modules in all deployments. 

Whereas, other times, even if we just rerun the pipeline run without making any code changes, some modules fail giving "No module named '...', 
for example in networking, no module named 'modules.vidigami_network',  
and the pipeline fails."

here's an error from the pipeline:
```
INFO:runway:---- Processing module 'networking' for 'production' in ca-central-1 --------------
INFO:runway:Module options: {'environments': {'production': {'testing_account_id': '', 'staging_account_id': '$V3_STAGING_ACCOUNT_ID', 'prod_account_id': '$V3_PROD_ACCOUNT_ID', 'sharedservices_account_id': ':"', 'namespace': 'vidigami-production', 'stacker_bucket_name': 'stacker-vidigami-bucket-ca-central-1-prod', 'prefix': 'vdm-production-cc1-', 'vidigami_domain_name': 'vidigami.com', 'environment': 'production', 'service_region': 'global', 'media_prefix': 'production', 'region': 'ca-central-1', 'edge_region': 'us-east-1', 'transcode_region': 'us-east-1', 'KMSKeyId': '', 'vidigami_certificate_test_ca_central_1': '', 'vidigami_certificate_stage_ca_central_1': '', 'vidigami_certificate_prod_ca_central_1': '', 'vidigami_certificate_test_us_east_1': '', 'vidigami_certificate_stage_us_east_1': '', 'vidigami_certificate_prod_us_east_1': '', 'pwa_bucket': 'production-global-web-vidi', 'media_bucket': 'production-global-media-vidi', 'media_original_bucket': 'production-global-original-media-vidi', 'yearbook_bucket': 'production-global-yearbooks-vidi', 'published_bucket': 'production-global-published-vidi', 'keypair_testing_ca_central_1': 'keypair-testing-ca-central-1', 'keypair_staging_ca_central_1': 'keypair-staging-ca-central-1', 'keypair_production_ca_central_1': 'keypair-production-ca-central-1'}}, 'options': {}, 'parameters': {'testing_account_id': '', 'staging_account_id': '$V3_STAGING_ACCOUNT_ID', 'prod_account_id': '$V3_PROD_ACCOUNT_ID', 'sharedservices_account_id': ':"', 'namespace': 'vidigami-production', 'stacker_bucket_name': 'stacker-vidigami-bucket-ca-central-1-prod', 'prefix': 'vdm-production-cc1-', 'vidigami_domain_name': 'vidigami.com', 'environment': 'production', 'service_region': 'global', 'media_prefix': 'production', 'region': 'ca-central-1', 'edge_region': 'us-east-1', 'transcode_region': 'us-east-1', 'KMSKeyId': '', 'vidigami_certificate_test_ca_central_1': '', 'vidigami_certificate_stage_ca_central_1': '', 'vidigami_certificate_prod_ca_central_1': '', 'vidigami_certificate_test_us_east_1': '', 'vidigami_certificate_stage_us_east_1': '', 'vidigami_certificate_prod_us_east_1': '', 'pwa_bucket': 'production-global-web-vidi', 'media_bucket': 'production-global-media-vidi', 'media_original_bucket': 'production-global-original-media-vidi', 'yearbook_bucket': 'production-global-yearbooks-vidi', 'published_bucket': 'production-global-published-vidi', 'keypair_testing_ca_central_1': 'keypair-testing-ca-central-1', 'keypair_staging_ca_central_1': 'keypair-staging-ca-central-1', 'keypair_production_ca_central_1': 'keypair-production-ca-central-1'}, 'name': 'networking', 'type': None, 'tags': {}, 'child_modules': [], 'class_path': None, 'env_vars': {}, 'path': 'networking', 'environment': True}
INFO:runway.cfngin:Found environment file: /opt/atlassian/pipelines/agent/build/production/networking/production-ca-central-1.env
INFO:runway.cfngin:stacks.yaml: deploying...
INFO:runway.cfngin:Using default AWS provider mode.
ERROR:runway.cfngin.plan:No module named 'modules.vidigami_network'
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/build-3vGKWv3F/lib/python3.7/site-packages/runway/cfngin/plan.py", line 142, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/root/.local/share/virtualenvs/build-3vGKWv3F/lib/python3.7/site-packages/runway/cfngin/actions/build.py", line 357, in _launch_stack
    stack.resolve(self.context, self.provider)
  File "/root/.local/share/virtualenvs/build-3vGKWv3F/lib/python3.7/site-packages/runway/cfngin/stack.py", line 232, in resolve
    self.blueprint.resolve_variables(self.variables)
  File "/root/.local/share/virtualenvs/build-3vGKWv3F/lib/python3.7/site-packages/runway/cfngin/stack.py", line 146, in blueprint
    blueprint_class = load_object_from_string(class_path)
  File "/root/.local/share/virtualenvs/build-3vGKWv3F/lib/python3.7/site-packages/runway/util.py", line 382, in load_object_from_string
    importlib.import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'modules.vidigami_network'
INFO:runway.cfngin.ui:networking: failed (No module named 'modules.vidigami_network')
INFO:runway.cfngin.ui:Endpoints: failed (dependency has failed)
ERROR:runway.cfngin.actions.base:The following steps failed: networking, Endpoints
```

We're using runway version 1.8.0 and the pipeline uses a python 3.7.2 image

Any ideas on that?

Thanks in advance!

**Comment by ITProKyle** [comment]
Please provide the full error being received and code that can be used to reproduce the issue so that we can investigate.

**Comment by rnour-onica** [comment]
@ITProKyle question updated, thanks.

**Comment by ITProKyle** [comment]
@rnour-onica - the information you provided is not enough to reproduce the issue. Please include **code** that can be used to reproduce this issue (e.g. an example repo).

I setup something similar to what you described and it works just fine for me. 

Double check your CFNgin config files to ensure you are providing the correct `sys_path`. Make sure you have the necessary `__init__.py` files in place so python can import your blueprints.

**Comment by ITProKyle** [comment]
closing as this was abandoned by the author. insufficient information was provided to reproduce and there have been subsequent patches released that address import issues.
