### ISSUE TITLE
`runway envvars` command will generate a "FailedVariableLookup" exception when AWS_REGION is used in parameters

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#355]
**Description**
If a deployment's `parameters` or `module_options` contains a `${env AWS_REGION}` lookup (depending on runway to set it during execution, the `runway envvars` command will throw an exception:

```
troyready@mycomp:~/myproj$ pipenv run runway envvars
INFO:runway:Could not find runway.variables.yml or runway.variables.yaml in the current directory. Continuing without a variables file.
INFO:runway:Deriving environment name from git branch ENV-prod...
INFO:runway:
INFO:runway:Environment "prod" was determined from the current git branch or parent directory.
INFO:runway:If this is not the environment name, update the branch/folder name or set an override value via the DEPLOY_ENVIRONMENT environment variable
INFO:runway:
Traceback (most recent call last):
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/variables.py", line 659, in resolve
    result = self.handler.handle(value=self.lookup_data.value,
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/lookups/handlers/env.py", line 80, in handle
    raise ValueError('"{}" does not exist in the environment'.format(value))
ValueError: "AWS_REGION" does not exist in the environment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/variables.py", line 102, in resolve
    self._value.resolve(context, provider=provider,
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/variables.py", line 428, in resolve
    item.resolve(context, provider=provider, variables=variables,
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/variables.py", line 428, in resolve
    item.resolve(context, provider=provider, variables=variables,
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/variables.py", line 678, in resolve
    raise FailedLookup(self, err)
runway.cfngin.exceptions.FailedLookup: Failed lookup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/bin/runway", line 11, in <module>
    load_entry_point('runway', 'console_scripts', 'runway')()
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/cli.py", line 91, in main
    command_class(cli_arguments).execute()
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/commands/runway/envvars.py", line 58, in execute
    deployment.resolve(context, self.runway_vars)
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/config.py", line 113, in resolve
    getattr(self, '_' + attr).resolve(context, variables=variables)
  File "/home/troyready/.local/share/virtualenvs/myproj-12345/src/runway/runway/variables.py", line 105, in resolve
    raise FailedVariableLookup(self.name, err.lookup, err.error)
runway.cfngin.exceptions.FailedVariableLookup: Couldn't resolve lookup in variable `deployment_1.module_options`, lookup: ${Lookup<Literal<'env'> Concatenation[Literal<'AWS_REGION'>]>}: (<class 'ValueError'>) "AWS_REGION" does not exist in the environment
```

**Expected behavior**
If there's only one region defined in the deployment, might be nice to have it automatically populate. Otherwise, some prompt to the user might be nice if it needs to be selected.

**Comment by ITProKyle** [comment]
A temporary workaround would be to `export AWS_REGION=us-east-1` or `AWS_REGION=us-east-1 runway envvars` to specify a region.
