### ISSUE TITLE
[BUG] Static module deploy fails

### ISSUE THREAD

**Issue by paul-duffy** [onicagroup/runway#360]
**Describe the bug**
When using the newest version of runway (1.8.1) static modules are not able to be deployed. The following error is show:

```
TypeError: <class 'troposphere.s3.BucketPolicy'>: BucketPolicy.PolicyDocument is <class 'awacs.aws.Policy'>, expected (<class 'dict'>, <class 'awacs.aws.Policy'>, <class 'awacs.aws.PolicyDocument'>)
```

**To Reproduce**
1. `pipenv --python 3`
2. `pipenv install -d runway==1.8.1`
3. `pipenv run runway gen-sample static-angular`
4. `cd static-angular`
5. `DEPLOY_ENVIRONMENT=dev pipenv run runway deploy`

```
ERROR:runway.cfngin.plan:<class 'troposphere.s3.BucketPolicy'>: BucketPolicy.PolicyDocument is <class 'awacs.aws.Policy'>, expected (<class 'dict'>, <class 'awacs.aws.Policy'>, <class 'awacs.aws.PolicyDocument'>)
Traceback (most recent call last):
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/runway/cfngin/plan.py", line 142, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/runway/cfngin/actions/build.py", line 360, in _launch_stack
    template = self._template(stack.blueprint)
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/runway/cfngin/actions/build.py", line 423, in _template
    return Template(body=blueprint.rendered)
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/runway/cfngin/blueprints/base.py", line 563, in rendered
    self._version, self._rendered = self.render_template()
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/runway/cfngin/blueprints/base.py", line 482, in render_template
    self.create_template()
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/runway/blueprints/staticsite/staticsite.py", line 148, in create_template
    self.add_bucket_policy(bucket)
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/runway/blueprints/staticsite/staticsite.py", line 329, in add_bucket_policy
    Join('', [bucket.get_att('Arn'), '/*'])
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/troposphere/__init__.py", line 127, in __init__
    self.__setattr__(k, v)
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/troposphere/__init__.py", line 214, in __setattr__
    self._raise_type(name, value, expected_type)
  File "/Users/pduffy/.local/share/virtualenvs/bugs-awxQH1y6/lib/python3.7/site-packages/troposphere/__init__.py", line 232, in _raise_type
    expected_type))
TypeError: <class 'troposphere.s3.BucketPolicy'>: BucketPolicy.PolicyDocument is <class 'awacs.aws.Policy'>, expected (<class 'dict'>, <class 'awacs.aws.Policy'>, <class 'awacs.aws.PolicyDocument'>)
INFO:runway.cfngin.ui:sample-app: failed (<class 'troposphere.s3.BucketPolicy'>: BucketPolicy.PolicyDocument is <class 'awacs.aws.Policy'>, expected (<class 'dict'>, <class 'awacs.aws.Policy'>, <class 'awacs.aws.PolicyDocument'>))
ERROR:runway.cfngin.actions.base:The following steps failed: sample-app
```

**Expected behavior**
The static site is deployed.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.4

**Additional context**
Works in version 1.8.0.

**Comment by ITProKyle** [comment]
This impacts all CFNgin modules using blueprints.

The root cause was introduced in #351 which unloads modules, including portions of awacs and troposphere. Because troposphere is being imported as part of the Blueprint base class's components, it is not completely unloaded. The remains result in type comparisons to class instances from the unloaded import which do not match subsequent imports.
