### ISSUE TITLE
[BUG] Runway failing to deploy terraform modules with certain syntax

### ISSUE THREAD

**Issue by aoggz** [onicagroup/runway#406]
**Describe the bug**
Runway v1.11.0 unable to deploy Terraform modules with certain syntax.

**To Reproduce**
1. Build a terraform configuration with questionable syntax.
2. Run `runway (plan|deploy)` with that terraform module.

**Expected behavior**
A deploy should occur as it did with the previous version of runway.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Version 10.15.6

**Additional context**
Below is the output of a `runway plan --verbose command`:
```sh
➜ runway plan --verbose
VERBOSE:runway.config:found config: /Users/aoggz/repos/repo/runway.yml
VERBOSE:runway.config:found variables file: /Users/aoggz/repos/repo/runway.variables.yml

Configured modules

1: api
2: infrastructure

Enter number of module to run (or "all") [all]: 2

INFO:runway.core.components.deploy_environment:deploy environment "dev" is explicitly defined in the environment
INFO:runway.core.components.deploy_environment:if not correct, update the value or unset it to fall back to the name of the current git branch or parent directory
VERBOSE:runway.config:deployment_1:resolving variables for pre-processing...
INFO:runway.core.components.deployment:
INFO:runway.core.components.deployment:
NOTICE:runway.core.components.deployment:deployment_1:processing deployment (in progress)
VERBOSE:runway.core.components.deployment:deployment_1:attempting to plan for the next deploy to region(s): us-east-1
INFO:runway.core.components.deployment:deployment_1:processing regions sequentially...
VERBOSE:runway.core.components.deployment:deployment_1:processing AWS region: us-east-1
VERBOSE:runway.core.components.deploy_environment:updated environment variables: {"AWS_DEFAULT_REGION": "us-east-1", "AWS_REGION": "us-east-1"}
VERBOSE:runway.config:deployment_1:resolving variables...
VERBOSE:runway.context:creating AWS session using credentials from the environment...
VERBOSE:runway.context:creating AWS session using credentials from the environment...
VERBOSE:runway.config:infrastructure:resolving variables...
INFO:runway.core.components.module:
NOTICE:runway.core.components.module:deployment_1.infrastructure:processing module in us-east-1 (in progress)
VERBOSE:runway.core.components.module:deployment_1.infrastructure:module payload: {"environments": {"dev": true, "test": true, "stage": true, "prod": true}, "options": {"terraform_backend_config": {"bucket": "***", "dynamodb_table": "zlv-***", "region": "us-east-1"}, "terraform_version": {"*": "0.12.24"}}, "parameters": {"param_1": "1"}, "name": "infrastructure", "type": null, "tags": {}, "child_modules": [], "class_path": null, "path": "infrastructure", "environment": true}
VERBOSE:runway.core.components.module:deployment_1.infrastructure:explicitly enabled
VERBOSE:runway.context:creating AWS session using credentials from the environment...
Traceback (most recent call last):
  File "runway-script.py", line 2, in <module>
  File "site-packages/click/core.py", line 829, in __call__
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/runway/_cli/main.py", line 34, in invoke
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "site-packages/click/decorators.py", line 21, in new_func
  File "site-packages/runway/_cli/commands/_plan.py", line 29, in plan
  File "site-packages/runway/core/__init__.py", line 110, in plan
  File "site-packages/runway/core/__init__.py", line 223, in __run_action
  File "site-packages/runway/core/components/_deployment.py", line 343, in run_list
  File "site-packages/runway/core/components/_deployment.py", line 203, in plan
  File "site-packages/runway/core/components/_deployment.py", line 303, in __sync
  File "site-packages/runway/core/components/_deployment.py", line 228, in run
  File "site-packages/runway/core/components/_module.py", line 317, in run_list
  File "site-packages/runway/core/components/_module.py", line 185, in plan
  File "site-packages/runway/core/components/_module.py", line 214, in run
  File "site-packages/runway/module/terraform.py", line 472, in plan
  File "site-packages/runway/module/terraform.py", line 447, in run
  File "site-packages/runway/module/terraform.py", line 210, in handle_backend
  File "site-packages/runway/util.py", line 74, in __get__
  File "site-packages/runway/env_mgr/tfenv.py", line 123, in backend
  File "site-packages/runway/util.py", line 74, in __get__
  File "site-packages/runway/env_mgr/tfenv.py", line 136, in terraform_block
  File "site-packages/hcl/api.py", line 81, in loads
  File "site-packages/hcl/parser.py", line 643, in parse
  File "site-packages/hcl/ply/yacc.py", line 330, in parse
  File "site-packages/hcl/lexer.py", line 391, in token
  File "site-packages/hcl/ply/lex.py", line 388, in token
  File "site-packages/hcl/lexer.py", line 364, in t_error
  File "site-packages/hcl/lexer.py", line 20, in _raise_error
ValueError: Line 173, column 36, index 4593: Illegal character '!'
[42523] Failed to execute script runway-script
```

Line 173 of the `main.tf` file is within the `locals { ... }` block and looks like this:
` is_lower_environment = ! contains(local.upper_environments, var.environment)`. This syntax is valid and was not a problem before runway 1.11.0.

If I remove the code that the parser is complaining about in that line, I just get an error for another line:
```sh
ValueError: Line 198, column 5750: unexpected COMMA; expected ADD, MINUS, MULTIPLY, DIVIDE
```
for the line setting the `domain_name` value:
```hcl
resource "aws_elasticsearch_domain" "main" {
  domain_name = lower(substr("${local.domain}-${var.environment}", 0, 27))
  ...
}
```

**Comment by ITProKyle** [comment]
> This syntax is valid and was not a problem before runway 1.11.0.

Runway <1.11 only parsed the hcl file if `terraform_version: min-required`. In 1.11.0, the hcl files in a module are now parsed to pull out the `backend` block to apply special handle for backends such as `remote`. This would be why the syntax worked pre-1.11.0.

This would be a bug in the hcl parser, [pyhcl](https://github.com/virtuald/pyhcl). Have you tried different versions of `pyhcl`?

**Comment by aoggz** [comment]
I have not, mainly because runway already depends on the latest version of that parser. I did notice that there are quite a few current open issues on that library regarding HCL compatibility, but none seemed specifically relevant to this issue.

**Comment by ITProKyle** [comment]
Is the syntax being used hcl or hcl2 (e.g. does it work with Terraform < 0.12)?

I _think_ the `pyhcl` library is hcl only but I would suggest creating an issue in their repo in case it is a bug with their hcl parsing or they would want to add some hlc2 (if it is hcl2). If no one on that end is able to resolve it fairly quickly, I may be able to take a crack at it. It's been a while since I have worked in that repo but I have added syntax support to it in the past.

I would be also be open to evaluating a different parser if there is a better option available but a quick google search does not uncover any that standout above the others. It looks like there is one aimed at hcl2 but we would need to ensure that it is also compatible with hcl.

**Comment by troyready** [comment]
@ITProKyle how about this insanity:

1) Bump Runway to v2
2) Drop Python <3.6 support
3) Change tf file loading to something approximating:

```python
import pyhcl as hcl1
import hcl2

try:
  hcl1.load('main.tf')
except:
  try:
    hcl2.load('main.tf')
  except:
    raise
```

It's horrible, but I'm not sure what we're supposed to do given [the state](https://github.com/virtuald/pyhcl/issues/75#issuecomment-668729361) of the [projects](https://github.com/amplify-education/python-hcl2#python-hcl2).

**Comment by ITProKyle** [comment]
@troyready you know I'm all for Runway v2 and all the things associated with it.

That is essentially the logic we will need to add. I would also lean towards dropping `pyhcl` into `extras_require` to cut down on install dependencies since its use would only be for older syntax. But, we would need to do some testing around just how _not backward compatible_ it is with hcl v1.

**Comment by ITProKyle** [comment]
I created a separate issue specific to adding HCL2 support - https://github.com/onicagroup/runway/issues/407
