### ISSUE TITLE
HCL parser errors aren't caught and don't give useful debugging information

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#546]
There are 2 primary cases where both parsers will bomb out:

1) Deploying a Terraform module with a bad config
2) Deploying a module with some new HCL syntax not supported by pyhcl2

I think we can improve the experience for both cases. For bad configs, it's useful to print the exception to give info on the error. For syntax errors (hopefully less common in the future), the exception is useful in pointing to syntax that can be adjusted to bypass the error.

**Comment by troyready** [comment]
Stacktrace from a recent deployment with some legitimately bad Terraform config:

```
VERBOSE:runway.env_mgr.tfenv:failed to parse as HCL2; trying HCL
Traceback (most recent call last):
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 59, in get_action
    return states[state][token.type]
KeyError: 'LESSTHAN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/env_mgr/tfenv.py", line 191, in terraform_block
    result = load_terrafrom_module(hcl2, self.path).get("terraform", {})
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/env_mgr/tfenv.py", line 122, in load_terrafrom_module
    tf_config = parser.loads(tf_file.read_text())
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/hcl2/api.py", line 18, in loads
    return hcl2.parse(text + "\n")
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/lark/lark.py", line 464, in parse
    return self.parser.parse(text, start=start)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/lark/parser_frontends.py", line 115, in parse
    return self._parse(token_stream, start)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/lark/parser_frontends.py", line 63, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 88, in parse
    action, arg = get_action(token)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 66, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token('LESSTHAN', '<') at line 228, column 16.
Expected one of: 
	* __ANON_10
	* LBRACE
	* __ANON_11
	* LSQB
	* MINUS
	* LPAR
	* BANG
	* STRING_LIT
	* DECIMAL
	* __ANON_3

DEBUG:runway.env_mgr.tfenv:using HCL parser to load module: /home/troyready/k8s-tf-infrastructure/eks-base.tf
DEBUG:runway.core.providers.aws.assume_role:no role was assumed; not reverting credentials
DEBUG:runway.core.providers.aws.assume_role:aws.AssumeRole context manager exited
Traceback (most recent call last):
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/bin/runway", line 8, in <module>
    sys.exit(cli())
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/_cli/main.py", line 31, in invoke
    return super(_CliGroup, self).invoke(ctx)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/_cli/commands/_deploy.py", line 41, in deploy
    Runway(ctx.obj.runway_config, ctx.obj.get_runway_context()).deploy(deployments)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/__init__.py", line 58, in deploy
    self.__run_action(
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/__init__.py", line 229, in __run_action
    components.Deployment.run_list(
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 368, in run_list
    cls(
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 187, in deploy
    return self.__sync("deploy")
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 331, in __sync
    self.run(action, region)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 238, in run
    Module.run_list(
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/components/_module.py", line 330, in run_list
    cls(
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/components/_module.py", line 170, in deploy
    return self.run("deploy")
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/core/components/_module.py", line 227, in run
    inst[action]()
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/module/terraform.py", line 491, in deploy
    self.run("apply")
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/module/terraform.py", line 460, in run
    self.handle_backend()
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/module/terraform.py", line 230, in handle_backend
    if not self.tfenv.backend["type"]:
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/util.py", line 71, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/env_mgr/tfenv.py", line 150, in backend
    for k, v in self.terraform_block.get("backend", {None: {}}).items()
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/util.py", line 71, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/env_mgr/tfenv.py", line 199, in terraform_block
    result = load_terrafrom_module(hcl, self.path).get("terraform", {})
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/runway/env_mgr/tfenv.py", line 122, in load_terrafrom_module
    tf_config = parser.loads(tf_file.read_text())
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/hcl/api.py", line 81, in loads
    return HclParser().parse(s, export_comments=export_comments)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/hcl/parser.py", line 642, in parse
    return self.yacc.parse(
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/hcl/ply/yacc.py", line 503, in parse
    tok = self.errorfunc(errtoken)
  File "/home/troyready/.local/share/virtualenvs/k8s-tf-infrastructure-IjwjZZQD/lib/python3.9/site-packages/hcl/parser.py", line 634, in p_error
    raise ValueError(msg)
ValueError: Line 41, column 842: unexpected IDENTIFIER; expected ASTERISK_PERIOD, LEFTPAREN, COMMA, LEFTBRACKET, RIGHTBRACKET, RIGHTPAREN, ADD, MINUS, MULTIPLY, DIVIDE
```
