### ISSUE TITLE
[BUG] runway 1.18.3 does not load hook from module root directory

### ISSUE THREAD

**Issue by newbeeeeeee** [onicagroup/runway#572]
I am having an issue where we have a few module that have hooks and were running version 1.4.4, when we upgraded to version 1.18.3, we are getting an error ModuleNotFoundError: No module named. The first hook works fine during the deploy and the subsequent one fails. It works when running from my local PC but fails in AWS codebuild. 

We added sys_path: ./ and our directory structure is like this:

```
module01
  templates
    template.yaml
  mod01_hooks_dir
    some_file.py
  stacker.yml

module02
  templates
    template.yaml
  mod02_hooks_dir
    some_file.py
  stacker.yml
```

in stacker.yml
```
sys_path: ./

pre_build:
  some_hook:
    mod01_hooks_dir.some_file.some_function

pre_build:
  some_hook:
    mod02_hooks_dir.some_file.some_function

```
**Expected behavior**
Runway should run all hooks as expected

**Screenshots**
```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/cfngin/hooks/utils.py", line 68, in handle_hooks
    method = load_object_from_string(hook.path, try_reload=True)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/util.py", line 554, in load_object_from_string
    importlib.import_module(module_path)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tgw_attach_hooks'
Shared resource transit_gateway is already accepted and active
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.6/bin/runway", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/_cli/main.py", line 31, in invoke
    return super(_CliGroup, self).invoke(ctx)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/_cli/commands/_takeoff.py", line 26, in takeoff
    ctx.forward(deploy, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 628, in forward
    return self.invoke(cmd, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/_cli/commands/_deploy.py", line 41, in deploy
    Runway(ctx.obj.runway_config, ctx.obj.get_runway_context()).deploy(deployments)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/__init__.py", line 59, in deploy
    "deploy", deployments if deployments is not None else self.deployments
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/__init__.py", line 234, in __run_action
    variables=self.variables,
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 373, in run_list
    )[action]()
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 187, in deploy
    return self.__sync("deploy")
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 331, in __sync
    self.run(action, region)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 244, in run
    variables=self._variables,
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/components/_module.py", line 336, in run_list
    )[action]()
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/components/_module.py", line 170, in deploy
    return self.run("deploy")
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/core/components/_module.py", line 227, in run
    inst[action]()
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/module/cloudformation.py", line 41, in deploy
    cfngin.deploy(force=self.options["environment"])
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/cfngin/cfngin.py", line 131, in deploy
    action.execute(concurrency=self.concurrency, tail=self.tail)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/cfngin/actions/base.py", line 160, in execute
    self.pre_run(**kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/cfngin/actions/build.py", line 527, in pre_run
    handle_hooks("pre_build", hooks, self.provider, self.context, dump, outline)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/cfngin/actions/build.py", line 194, in handle_hooks
    utils.handle_hooks(stage=stage, hooks=hooks, provider=provider, context=context)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/cfngin/hooks/utils.py", line 68, in handle_hooks
    method = load_object_from_string(hook.path, try_reload=True)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/runway/util.py", line 554, in load_object_from_string
    importlib.import_module(module_path)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tgw_attach_hooks'
```

**Additional context**
If I revert back to 1.4.4, it works fine.

**Comment by ITProKyle** [comment]
Can you please provide the version of python being used on your local machine? I see from the error that 3.7.6 is being used by CodeBuild.

Can you also please provide an example repo that can be used to reproduce this issue?

----

With the information provided, I can infer the most likely cause for it working locally but not when using CodeBuild is due to the versions of python being used and how the import system of the different versions of python work. I don't see any `__init__.py` files in the directory structure posted which supports this being at least partially the cause.

In the example `stacker.yml`, I see a `mod01_hooks_dir` & `mod02_hooks_dir` being used. These appear to exist in two different Runway modules/directories which would make `./` an insufficient `sys_path` as it would only allow for the import of python packages from within the same directory. Runway 1.4.0 contained a bug that caused all imported python packages to remain _loaded_ and all sys path entries to be retained between Runway modules. This would have allowed your current configuration file to work even through it contains errors. The imports remaining loaded bug was patched in [1.8.1](https://github.com/onicagroup/runway/blob/master/CHANGELOG.md#181---2020-06-04) and the sys path bug was later patched in [1.8.3](https://github.com/onicagroup/runway/blob/master/CHANGELOG.md#183---2020-06-24).

So, to have your config and directory structure work, you would need to add `__init__.py` files at each level in accordance with [6.4 Packages](https://docs.python.org/3.7/tutorial/modules.html#packages). After those are added, your `sys_path` would need to be `./../`. This would then allow you to import your hooks as `module01.mod01_hooks_dir.some_file.some_function` & `module02.mod02_hooks_dir.some_file.some_function`.

If you have any questions, please let me know.

**Comment by newbeeeeeee** [comment]
Hello @ITProKyle , 
Thanks for your response. I am using version 3.8.5 on my computer and codebuild is set to latest 3.7. I can ensure that codebuid get upgraded to 3.8. We also have it set to codebuild standard amazon linux 2 docker image (version 2.0).  I was not aware of using ```./../``` for sys_path and why runway 1.4.4 works with no sys_path makes total sense now. 

I do have __init__.py file in every module's hook directory, I forgot to mention it when I opened the bug. I will complete this work after hours over a weekend and get back to you to see if it resolves the issue. 

I appreciate your time on this.

**Comment by ITProKyle** [comment]
> I am using version 3.8.5 on my computer

Great! So it _shouldn't_ be a mismatch in import functionality. The biggest places this occurs is python 2 vs 3.

> I was not aware of using `./../` for sys_path... I do have `__init__.py` file in every module's hook directory

For `./../` to work, you would also want to add an init file to to root of the Runway module directory (e.g. `module01/__init__.py`). There needs to be one at each level you are trying to traverse with python importing.

To get a better idea of the paths that a python import can see while Runway is importing hooks, you can add the `--debug` flag. It will add a lot of additional output but most importantly it will display the value of `sys.path` and `sys.modules` as they are being added to and reverted between the execution of each Runway module. You can use these values to ensure the expected path is being added.

**Comment by ITProKyle** [comment]
@newbeeeeeee - Were you able to sort out the import issue?

**Comment by newbeeeeeee** [comment]
@ITProKyle , Thanks for following up. I have scheduled the upgrade tonight and I will update tomorrow morning.

**Comment by newbeeeeeee** [comment]
@ITProKyle , The change you suggested worked perfectly. Runway was able to find all the hooks and run them like it did in older version. Thanks for all your help.
