### ISSUE TITLE
[QUESTION] Unexpected Behavior When Deploying Modules in Parallel

### ISSUE THREAD

**Issue by vinceoan** [onicagroup/runway#643]
**Question**
How runway manage python library when deployed in parallel? Does each module run on its own virutalenv or all modules share same virutalenv?

**Context**
We are experiencing some arbitrary unexpected behavior when using parallel to deploy modules. Basically we have a hook that use a python library in some modules, and not in some other modules. When deployed in parallel we have ran into `ModuleNotFoundError: No module named.....` And it does not happen all the time, just sometimes, which make it difficult to understand what is really happening. My suspicious is assuming all modules share same virtualenv then somehow they step over each other that caused ModuleNotFoundError. Really need some expert here to give us insight.

**Comment by ITProKyle** [comment]
> How runway manage python library when deployed in parallel? 

Runway does not _"manage python library"_. It does _unload_ imported python packages between modules.

> Does each module run on its own virutalenv or all modules share same virutalenv?

It runs the modules using the same interpreter that Runway is running from. Whether you are running Runway using a virtual environment or not. Running in parallel just means there are different processing being spawned to do the work.

Without having more information, there's not much help I can provide. Can you please provide an example project, version of python, version of Runway, operating system, full error, etc.

**Comment by vinceoan** [comment]
I see. Sure I will try put everything together as an example project. I'm running using Runway 1.15, Python 3.7, and OS Amazon Linux 2. Quick question on parallel. Let's say I have 6 modules in parallel will Runway spawn all 6 threads to process them or any cap limit on that?

**Comment by vinceoan** [comment]
@ITProKyle I've packed this sample runway project into docker container. Once assumed rule, you can use this command to run the container.
`export AWS_PROFILE=$AWS_DEFAULT_PROFILE
docker run --rm -i \
--env AWS_PROFILE \
--env AWS_SHARED_CREDENTIALS_FILE=/aws/credentials \
--env AWS_CONFIG_FILE=/aws/config \
--env AWS_DEFAULT_REGION=us-east-1 \
--env AWS_SDK_LOAD_CONFIG=1 \
--env CI=1 \
--env DEPLOY_ENVIRONMENT=dev0 \
--env GIT_BRANCH=dev0 \
-v ~/.aws:/aws \
docker.io/voanhub/example-runway-parallel-project`
you can also login into the container to see runway project content.
This is the error I got when running in parallel.
`ModuleNotFoundError: No module named 'ccplatcfnginlibs'
[runway] 
[runway] 00-main.105-module-template-test5:processing module in us-east-1 (in progress)
[runway] found environment file: /runway/105-module-template-test5/dev0.env
[runway] stacker.yaml:deploy (in progress)
[runway] executing pre_build hooks: libs.hooks.ccplat_pre_build.hook
[runway] unable to load method at libs.hooks.ccplat_pre_build.hook
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/runway/cfngin/hooks/utils.py", line 68, in handle_hooks
    method = load_object_from_string(hook.path, try_reload=True)
  File "/usr/local/lib/python3.7/site-packages/runway/util.py", line 550, in load_object_from_string
    importlib.import_module(module_path)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libs'
[runway] 
[runway] 00-main.106-module-template-test6:processing module in us-east-1 (in progress)
[runway] found environment file: /runway/106-module-template-test6/dev0.env
[runway] stacker.yaml:deploy (in progress)
[runway] executing pre_build hooks: libs.hooks.ccplat_pre_build.hook
[runway] unable to load method at libs.hooks.ccplat_pre_build.hook
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/runway/cfngin/hooks/utils.py", line 68, in handle_hooks
    method = load_object_from_string(hook.path, try_reload=True)
  File "/usr/local/lib/python3.7/site-packages/runway/util.py", line 550, in load_object_from_string
    importlib.import_module(module_path)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libs'
{"Name": "None", "LevelNo": 20, "LevelName": "INFO", "PathName": "./ccplatcfnginlibs/helpers/hooks.py", "FileName": "hooks.py", "Module": "hooks", "LineNo": 9, "Created": 1623371677.052998, "AscTime": "2021-06-11 00:34:37,052", "MSecs": 52.99806594848633, "RelativeCreated": 39993.04962158203, "Thread": 140240302540608, "ThreadName": "MainThread", "Process": 39, "Message": "[] Executing hook ccplatcfnginlibs.hooks.apigateway_service_role.hook"}
{"Name": "None", "LevelNo": 20, "LevelName": "INFO", "PathName": "./ccplatcfnginlibs/hooks/apigateway_service_role.py", "FileName": "apigateway_service_role.py", "Module": "apigateway_service_role", "LineNo": 14, "Created": 1623371677.0571623, "AscTime": "2021-06-11 00:34:37,057", "MSecs": 57.16228485107422, "RelativeCreated": 39997.21384048462, "Thread": 140240302540608, "ThreadName": "MainThread", "Process": 39, "Message": "[] Running hook for module: cloud-common-template-module-test1"}
[runway] hello-test1:skipped (nochange)
[runway] stacker.yaml:deploy (complete)
[runway] 00-main.101-module-template-test1:processing module in us-east-1 (complete)
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_module.py", line 227, in run
    inst[action]()
  File "/usr/local/lib/python3.7/site-packages/runway/module/cloudformation.py", line 41, in deploy
    cfngin.deploy(force=self.options["environment"])
  File "/usr/local/lib/python3.7/site-packages/runway/cfngin/cfngin.py", line 131, in deploy
    action.execute(concurrency=self.concurrency, tail=self.tail)
  File "/usr/local/lib/python3.7/site-packages/runway/cfngin/actions/base.py", line 160, in execute
    self.pre_run(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/runway/cfngin/actions/build.py", line 527, in pre_run
    handle_hooks("pre_build", hooks, self.provider, self.context, dump, outline)
  File "/usr/local/lib/python3.7/site-packages/runway/cfngin/actions/build.py", line 194, in handle_hooks
    utils.handle_hooks(stage=stage, hooks=hooks, provider=provider, context=context)
  File "/usr/local/lib/python3.7/site-packages/runway/cfngin/hooks/utils.py", line 68, in handle_hooks
    method = load_object_from_string(hook.path, try_reload=True)
  File "/usr/local/lib/python3.7/site-packages/runway/util.py", line 550, in load_object_from_string
    importlib.import_module(module_path)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libs'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/runway", line 33, in <module>
    sys.exit(load_entry_point('runway==1.15.0', 'console_scripts', 'runway')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/runway/_cli/main.py", line 31, in invoke
    return super(_CliGroup, self).invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/runway/_cli/commands/_takeoff.py", line 26, in takeoff
    ctx.forward(deploy, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 628, in forward
    return self.invoke(cmd, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/runway/_cli/commands/_deploy.py", line 41, in deploy
    Runway(ctx.obj.runway_config, ctx.obj.get_runway_context()).deploy(deployments)
  File "/usr/local/lib/python3.7/site-packages/runway/core/__init__.py", line 59, in deploy
    "deploy", deployments if deployments is not None else self.deployments
  File "/usr/local/lib/python3.7/site-packages/runway/core/__init__.py", line 234, in __run_action
    variables=self.variables,
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 373, in run_list
    )[action]()
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 187, in deploy
    return self.__sync("deploy")
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 331, in __sync
    self.run(action, region)
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_deployment.py", line 244, in run
    variables=self._variables,
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_module.py", line 336, in run_list
    )[action]()
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_module.py", line 172, in deploy
    return self.__async("deploy")
  File "/usr/local/lib/python3.7/site-packages/runway/core/components/_module.py", line 257, in __async
    job.result()  # raise exceptions / exit as needed
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ModuleNotFoundError: No module named 'libs'`

**Comment by ITProKyle** [comment]
@vinceoan - can you please provide the example project as a repository? Having it in a docker container is not very helpful as I can't easily see what's going on.

**Comment by vinceoan** [comment]
@ITProKyle here is the repo.
https://github.com/vinceoan/example-runway-parallel-project

**Comment by ITProKyle** [comment]
Looking over your your example repo, you are trying to use hooks from a module that does not exist. For example 102-106 are trying to use hooks from `libs` but none of them have a `libs` module in their `sys_path`.

As for this working when not run in parallel, it shouldn't. The only way it _could_ work is if the system running it has a `libs` module somewhere in its path.

**Comment by ITProKyle** [comment]
@vinceoan - were you able to sort out what was going on?

**Comment by vincentko89** [comment]
@ITProKyle thanks for following up. Yes upon upgrading those modules to latest version it fixed the problem. I doubt there were some bad import code among one of earlier version that we built that missing the libs library from the module root directory.
