### ISSUE TITLE
Unable to runway plan on a k8s manifest in v2.0.1

### ISSUE THREAD

**Issue by samispurs** [onicagroup/runway#660]
**Describe the bug**
runway plan or deploy not working as expected with version 2.0.1, works fine in 1.18.3

Error: got file 'kustomization.yaml', 'k8s/sealedsecrets.k8s/overlays/qa/kustomization.yaml' must be a directory to be a root
subprocess.CalledProcessError: Command '['kubectl', 'kustomize', 'k8s/sealedsecrets.k8s/overlays/qa/kustomization.yaml']' returned non-zero exit status 1.

**To Reproduce**

1. use version 2.0.1
2. 

**Expected behavior**
runway should produce the yaml file based on the k8s overlays

**Desktop (please complete the following information):**

- OS: [e.g. MacOS]

**Comment by ITProKyle** [comment]
@samispurs - can you please provide a simple example repository capable of reproducing the bug? I'm not all that familiar with Kubernetes so it would save me quite a bit of time. If you can, I would likely be able to patch this tomorrow.

**Comment by samispurs** [comment]
@ITProKyle Have setup a test repo https://github.com/samispurs/runway-k8s

Under 1.18.3 used
runway plan --deploy-environment dev


```
[runway] could not find runway.variables.yml or runway.variables.yaml in the current directory; continuing without a variables file
[runway] deploy environment "dev" is explicitly defined in the environment
[runway] if not correct, update the value or unset it to fall back to the name of the current git branch or parent directory
[runway]
[runway]
[runway] eks-dev-cluster:processing deployment (in progress)
[runway] eks-dev-cluster:processing regions sequentially...
[runway]
[runway] eks-dev-cluster.aws/infrastructure/k8s/configmaps.k8s:processing module in us-west-2 (in progress)
[runway] processing kustomize overlay: /Users/samp/Work/Personal/github/repo-runway-k8s/runway-k8s/aws/infrastructure/k8s/configmaps.k8s/overlays/dev/kustomization.yaml
[runway] aws/infrastructure/k8s/configmaps.k8s:yaml was generated by kubectl:

apiVersion: v1
data:
  foo: bar2
kind: ConfigMap
metadata:
  name: test-configmap
  namespace: dev

[runway] eks-dev-cluster.aws/infrastructure/k8s/configmaps.k8s:processing module in us-west-2 (complete)
[runway] eks-dev-cluster:processing deployment (complete)

```
With 2.0.1

```
(repo-runway-k8s) samp@Samirs-MacBook-Pro runway-k8s % pip install runway==2.0.1
Collecting runway==2.0.1
  Using cached runway-2.0.1-py3-none-any.whl
Requirement already satisfied: boto3>=1.16.36<2.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.17.92)
Requirement already satisfied: pyhcl~=0.4 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (0.4.4)
Collecting pydantic>=1.4.0
  Using cached pydantic-1.8.2-cp39-cp39-macosx_10_9_x86_64.whl (2.7 MB)
Requirement already satisfied: gitpython in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (3.1.17)
Requirement already satisfied: Send2Trash in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.5.0)
Requirement already satisfied: requests in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (2.25.1)
Requirement already satisfied: PyYAML>=5 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (5.2)
Requirement already satisfied: botocore>=1.19.36<2.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.20.92)
Requirement already satisfied: cfn-lint in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (0.48.3)
Requirement already satisfied: click>=7.1 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (8.0.1)
Requirement already satisfied: coloredlogs in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (15.0.1)
Requirement already satisfied: yamllint in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.26.1)
Requirement already satisfied: packaging in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (20.9)
Requirement already satisfied: cfn-flip>=1.2.1 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.2.3)
Requirement already satisfied: pyOpenSSL in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (20.0.1)
Requirement already satisfied: formic2 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.0.3)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.25.11)
Requirement already satisfied: python-hcl2~=2.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (2.0.3)
Requirement already satisfied: awacs in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.0.4)
Requirement already satisfied: docker in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (5.0.0)
Collecting typing-extensions
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Requirement already satisfied: zgitignore in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (1.0.0)
Requirement already satisfied: troposphere>=2.4.2 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (2.7.1)
Requirement already satisfied: jinja2<3.0,>=2.7 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from runway==2.0.1) (2.11.3)
Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from boto3>=1.16.36<2.0->runway==2.0.1) (0.4.2)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from boto3>=1.16.36<2.0->runway==2.0.1) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from botocore>=1.19.36<2.0->runway==2.0.1) (2.8.1)
Requirement already satisfied: six in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cfn-flip>=1.2.1->runway==2.0.1) (1.16.0)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from jinja2<3.0,>=2.7->runway==2.0.1) (2.0.1)
Requirement already satisfied: lark-parser<0.11.0,>=0.10.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from python-hcl2~=2.0->runway==2.0.1) (0.10.1)
Requirement already satisfied: aws-sam-translator>=1.34.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cfn-lint->runway==2.0.1) (1.36.0)
Requirement already satisfied: jsonpatch in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cfn-lint->runway==2.0.1) (1.32)
Requirement already satisfied: junit-xml~=1.9 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cfn-lint->runway==2.0.1) (1.9)
Requirement already satisfied: jsonschema~=3.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cfn-lint->runway==2.0.1) (3.2.0)
Requirement already satisfied: networkx~=2.4 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cfn-lint->runway==2.0.1) (2.5.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from jsonschema~=3.0->cfn-lint->runway==2.0.1) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from jsonschema~=3.0->cfn-lint->runway==2.0.1) (21.2.0)
Requirement already satisfied: setuptools in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from jsonschema~=3.0->cfn-lint->runway==2.0.1) (54.2.0)
Requirement already satisfied: decorator<5,>=4.3 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from networkx~=2.4->cfn-lint->runway==2.0.1) (4.4.2)
Requirement already satisfied: humanfriendly>=9.1 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from coloredlogs->runway==2.0.1) (9.2)
Requirement already satisfied: websocket-client>=0.32.0 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from docker->runway==2.0.1) (1.1.0)
Requirement already satisfied: idna<3,>=2.5 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from requests->runway==2.0.1) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from requests->runway==2.0.1) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from requests->runway==2.0.1) (4.0.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from gitpython->runway==2.0.1) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->gitpython->runway==2.0.1) (4.0.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from jsonpatch->cfn-lint->runway==2.0.1) (2.1)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from packaging->runway==2.0.1) (2.4.7)
Requirement already satisfied: cryptography>=3.2 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from pyOpenSSL->runway==2.0.1) (3.4.7)
Requirement already satisfied: cffi>=1.12 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cryptography>=3.2->pyOpenSSL->runway==2.0.1) (1.14.5)
Requirement already satisfied: pycparser in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=3.2->pyOpenSSL->runway==2.0.1) (2.20)
Requirement already satisfied: pathspec>=0.5.3 in /Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages (from yamllint->runway==2.0.1) (0.8.1)
Installing collected packages: typing-extensions, pydantic, runway
  Attempting uninstall: runway
    Found existing installation: runway 1.18.3
    Uninstalling runway-1.18.3:
      Successfully uninstalled runway-1.18.3
Successfully installed pydantic-1.8.2 runway-2.0.1 typing-extensions-3.10.0.0
(repo-runway-k8s) samp@Samirs-MacBook-Pro runway-k8s %
(repo-runway-k8s) samp@Samirs-MacBook-Pro runway-k8s %
(repo-runway-k8s) samp@Samirs-MacBook-Pro runway-k8s %
(repo-runway-k8s) samp@Samirs-MacBook-Pro runway-k8s %
(repo-runway-k8s) samp@Samirs-MacBook-Pro runway-k8s % export AWS_PROFILE=opi-prod;runway plan --deploy-environment dev
[runway] could not find runway.variables.yml or runway.variables.yaml in the current directory; continuing without a variables file
[runway] deploy environment "dev" is explicitly defined in the environment
[runway] if not correct, update the value or unset it to fall back to the name of the current git branch or parent directory
[runway]
[runway]
[runway] eks-dev-cluster:processing deployment (in progress)
[runway] eks-dev-cluster:processing regions sequentially...
[runway]
[runway] eks-dev-cluster.configmaps.k8s:processing module in us-west-2 (in progress)
[runway] processing kustomize overlay: /Users/samp/Work/Personal/github/repo-runway-k8s/runway-k8s/aws/infrastructure/k8s/configmaps.k8s/overlays/dev/kustomization.yaml
Error: got file 'kustomization.yaml', but '/Users/samp/Work/Personal/github/repo-runway-k8s/runway-k8s/aws/infrastructure/k8s/configmaps.k8s/overlays/dev/kustomization.yaml' must be a directory to be a root
Traceback (most recent call last):
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/bin/runway", line 8, in <module>
    sys.exit(cli())
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/_cli/main.py", line 33, in invoke
    return super().invoke(ctx)
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/_cli/commands/_plan.py", line 44, in plan
    Runway(ctx.obj.runway_config, ctx.obj.get_runway_context()).plan(
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/__init__.py", line 115, in plan
    self.__run_action(
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/__init__.py", line 239, in __run_action
    components.Deployment.run_list(
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 290, in run_list
    cls(
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 145, in plan
    return self.__sync("plan")
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 255, in __sync
    self.run(action, region)
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/components/_deployment.py", line 164, in run
    Module.run_list(
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/components/_module.py", line 306, in run_list
    cls(
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/components/_module.py", line 199, in plan
    return self.run("plan")
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/core/components/_module.py", line 229, in run
    inst[action]()
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/module/k8s.py", line 157, in plan
    self.run_kubectl(command="plan")
  File "/Users/samp/.local/share/virtualenvs/repo-runway-k8s-MphI_P1I/lib/python3.9/site-packages/runway/module/k8s.py", line 136, in run_kubectl
    kustomize_yml = subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['kubectl', 'kustomize', '/Users/samp/Work/Personal/github/repo-runway-k8s/runway-k8s/aws/infrastructure/k8s/configmaps.k8s/overlays/dev/kustomization.yaml']' returned non-zero exit status 1.
```

Hope this helps

**Comment by ITProKyle** [comment]
@samispurs - thanks for the help. I was able to identify the issue and the patch should be released within the next two hours.

**Comment by samispurs** [comment]
@ITProKyle I also created a tag issue under https://github.com/samispurs/runway-k8s/tree/tag_issue,  When using - path: for multiple modules the - tags: will not work.  If I apply tags as follows

```
modules:      
  - path: aws/infrastructure/k8s/configmaps.k8s 
  - path: module2
  - path: module3
     tags: #Using example from https://docs.onica.com/projects/runway/en/release/runway_config.html#module.tags 
        - new_tag 
        - old_tag
```

tags is only applicable to the last - path listed.
Not sure if that is a bug or the way the runway file was created which is incorrect. 

Thanks!

**Comment by ITProKyle** [comment]
@samispurs - this would be correct if you are trying to define `tags` for `module3`. `tags` is a field of a module, just like `path` is.

```yaml
modules:      
  - path: aws/infrastructure/k8s/configmaps.k8s 
  - path: module2
  - path: module3
    tags:
      - new_tag 
      - old_tag
```

**Comment by samispurs** [comment]
When running: runway deploy --deploy-environment dev --tag new_tag
If found that it only applies to module3.  The first two modules are not included.  Is that the correct behaviour.  I would have thought tags should apply to all modules listed under name.

```
- name: eks-dev-cluster
    modules:
      - path: aws/infrastructure/k8s/configmaps.k8s
      - path: module2
      - path: module3
      - tags: #Using example from https://docs.onica.com/projects/runway/en/release/runway_config.html#module.tags
          - new_tag
          - old_tag
```
Thanks!

**Comment by ITProKyle** [comment]
That is the correct behavior. `tags` is a module field not a deployment field. `aws/infrastructure/k8s/configmaps.k8s` is one module `module3` is another module. each have their own `tags` field that would need to be defined separately.

As for how you have the above currently written, `tags` would only apply to the 4th module in the list which would be the equivalent of

```yaml
    modules:
     ...
      - path: ./ # the current working directory
        tags:
          - new_tag
          - old_tag
```

**Comment by ITProKyle** [comment]
@samispurs - Runway 2.1.1 is now available on PyPi if you want to give it a try. The other distributions will be updated as their builds finish over the next ~15 minutes.

**Comment by samispurs** [comment]
@ITProKyle Working as expected. Thank you for addressing this so promptly. Cheers!
